######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 10 13:25:03 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . UI
INCLUDEPATH += . UI

# Input
HEADERS += Adaboost.h PCASVM.h rtimer.h YCbCr.h UI/Main.h
FORMS += UI/FaceDetactUI.ui
SOURCES += Adaboost.cpp PCASVM.cpp rtimer.cpp YCbCr.cpp UI/Main.cpp UI/test.cpp
RESOURCES += UI/mySrc.qrc
