######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 9 21:24:13 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Main.h
FORMS += FaceDetactUI.ui
SOURCES += Main.cpp test.cpp
RESOURCES += mySrc.qrc
